package dev.emptyhans.nicknamegenerator;
import android.app.*;import android.os.*;import android.graphics.*;import android.content.*;import android.net.*;import android.provider.*;import android.database.*;import android.view.*;import android.widget.*;import java.io.*;import java.nio.*;import java.nio.charset.*;import java.util.*;import java.util.regex.*;
public class MainActivity extends Activity{
 static final int OPEN=41;final Random r=new Random();LinearLayout options,results;Spinner mode;TextView status;Csv csv;final List<Row> rows=new ArrayList<>();
 static class Row{String[] words;CheckBox use;Spinner pos;Row(String[]w){words=w;}}
 static class Csv{LinkedHashMap<String,List<String>> cols=new LinkedHashMap<>();List<String> patterns=new ArrayList<>();String name="data.csv";}
 final String[] family={"星宮","月城","白石","雨宮","神代","天羽","黒川","桜庭","水瀬","柊木","朝霧","御影","風間","雪村","一ノ瀬","七海"},given={"ルナ","ミコト","レイ","シオン","カナデ","アオイ","ヒカリ","ユラ","ノア","スイ","トワ","リリカ","ナギ","セナ"},title={"深夜の司書","電脳の吟遊詩人","無重力の料理人","黄昏の観測者","路地裏の錬金術師","静寂の収集家","月面喫茶の店主","異界の編集者"},food={"焦がし月光のカルボナーラ","星屑仕立てのオムライス","深夜喫茶の固めプリン","黄昏果実のタルト","白夜仕込みのビーフシチュー","雨音香るスコーン"},penF={"余白","常盤","久遠","白群","薄明","灯里","紙屋","綴木","青磁","冬青"},penG={"栞","朔","澄","綴","環","凪","透","灯","律","墨"},elements={"月","星","雨","白","黒","夢","夜","空","音","光","花","雪","風","海","天","影"};
 @Override public void onCreate(Bundle b){super.onCreate(b);build();load();}
 TextView tv(String s,int z,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.rgb(24,28,32));v.setTypeface(null,bold?1:0);v.setPadding(0,8,0,8);return v;}
 void build(){ScrollView sc=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(36,40,36,60);root.setBackgroundColor(Color.rgb(244,242,237));sc.addView(root);root.addView(tv("NAME LAB / 10",28,true));root.addView(tv("偶然性から、使える名前を拾う。",14,false));mode=new Spinner(this);mode.setAdapter(adapter(new String[]{"架空VTuber名","ペンネーム","二つ名・肩書き","架空の料理名","漢字シャッフル名","インポートCSV"}));root.addView(mode,new LinearLayout.LayoutParams(-1,64));Button imp=new Button(this);imp.setText("CSVを読み込む");imp.setOnClickListener(v->open());root.addView(imp,new LinearLayout.LayoutParams(-1,64));status=tv("CSV：未読込",13,false);root.addView(status);root.addView(tv("必ず含める要素 / 配置",16,true));options=new LinearLayout(this);options.setOrientation(LinearLayout.VERTICAL);root.addView(options);add("月・夜",new String[]{"月","夜","宵","ルナ"});add("自然",new String[]{"雨","風","雪","花","森","海"});add("幻想",new String[]{"夢","幻","異界","星屑","黄昏"});add("創作",new String[]{"綴","絵","本","詩","音"});Button gen=new Button(this);gen.setText("10個生成する");gen.setTextSize(18);gen.setOnClickListener(v->generate());root.addView(gen,new LinearLayout.LayoutParams(-1,72));results=new LinearLayout(this);results.setOrientation(LinearLayout.VERTICAL);root.addView(results);setContentView(sc);generate();}
 ArrayAdapter<String> adapter(String[]s){return new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,s);}
 void add(String label,String[]words){Row x=new Row(words);LinearLayout line=new LinearLayout(this);line.setGravity(16);x.use=new CheckBox(this);x.use.setText(label);x.pos=new Spinner(this);x.pos.setAdapter(adapter(new String[]{"自動","先頭","P1の後","P2の後","P3の後","P4の後","P5の後","P6の後","末尾"}));line.addView(x.use,new LinearLayout.LayoutParams(0,60,1));line.addView(x.pos,new LinearLayout.LayoutParams(0,60,1));options.addView(line);rows.add(x);}
 void open(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");try{startActivityForResult(i,OPEN);}catch(Exception e){Intent j=new Intent(Intent.ACTION_GET_CONTENT);j.addCategory(Intent.CATEGORY_OPENABLE);j.setType("*/*");startActivityForResult(Intent.createChooser(j,"CSVを選択"),OPEN);}}
 @Override protected void onActivityResult(int q,int result,Intent data){super.onActivityResult(q,result,data);if(q!=OPEN||result!=RESULT_OK||data==null)return;try{Uri u=data.getData();String body=decode(read(getContentResolver().openInputStream(u)));Csv x=parse(body);x.name=fileName(u);save(body,x.name);csv=x;showStatus();mode.setSelection(5);generate();Toast.makeText(this,"CSVを読み込みました",0).show();}catch(Exception e){Toast.makeText(this,"読込エラー："+e.getMessage(),1).show();}}
 byte[] read(InputStream in)throws IOException{ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]b=new byte[8192];int n;while((n=in.read(b))>=0)o.write(b,0,n);in.close();return o.toByteArray();}
 String decode(byte[]b)throws Exception{int off=b.length>2&&(b[0]&255)==239&&(b[1]&255)==187&&(b[2]&255)==191?3:0;CharsetDecoder d=StandardCharsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).onUnmappableCharacter(CodingErrorAction.REPORT);try{return d.decode(ByteBuffer.wrap(b,off,b.length-off)).toString();}catch(Exception e){return new String(b,Charset.forName("MS932"));}}
 String fileName(Uri u){try(Cursor c=getContentResolver().query(u,null,null,null,null)){if(c!=null&&c.moveToFirst()){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(i>=0)return c.getString(i);}}catch(Exception e){}return"data.csv";}
 void save(String body,String name)throws IOException{try(Writer w=new OutputStreamWriter(openFileOutput("imported.csv",0),StandardCharsets.UTF_8)){w.write(body);}try(Writer w=new OutputStreamWriter(openFileOutput("imported.name",0),StandardCharsets.UTF_8)){w.write(name);}}
 void load(){try{csv=parse(new String(read(openFileInput("imported.csv")),StandardCharsets.UTF_8));try{csv.name=new String(read(openFileInput("imported.name")),StandardCharsets.UTF_8);}catch(Exception e){}showStatus();}catch(Exception e){showStatus();}}
 void showStatus(){if(csv==null){status.setText("CSV：未読込");return;}int n=0;for(List<String>x:csv.cols.values())n+=x.size();status.setText("CSV："+csv.name+" / "+csv.cols.size()+"列 / "+n+"語 / "+csv.patterns.size()+"パターン");}
 Csv parse(String text)throws Exception{List<List<String>>t=table(text);if(t.isEmpty())throw new Exception("CSVが空です");Csv d=new Csv();List<String>h=t.get(0);for(String s:h){s=clean(s);if(!pattern(s)&&!s.isEmpty())d.cols.put(s,new ArrayList<>());}for(int y=1;y<t.size();y++)for(int x=0;x<h.size();x++){String k=clean(h.get(x)),v=x<t.get(y).size()?t.get(y).get(x).trim():"";if(v.isEmpty())continue;List<String>dest=pattern(k)?d.patterns:d.cols.get(k);if(dest!=null&&!has(dest,v))dest.add(v);}if(d.cols.isEmpty())throw new Exception("見出し列がありません");if(d.patterns.isEmpty()){StringBuilder p=new StringBuilder();for(String k:d.cols.keySet())if(!d.cols.get(k).isEmpty())p.append("[").append(k).append("]");d.patterns.add(p.toString());}return d;}
 boolean pattern(String s){return s.equalsIgnoreCase("pattern")||s.equalsIgnoreCase("patterns");}String clean(String s){return s.replace("\uFEFF","").trim();}boolean has(List<String>a,String v){for(String s:a)if(s.equalsIgnoreCase(v))return true;return false;}
 List<List<String>>table(String s){List<List<String>>all=new ArrayList<>();List<String>row=new ArrayList<>();StringBuilder c=new StringBuilder();boolean q=false;for(int i=0;i<s.length();i++){char z=s.charAt(i);if(z=='"'){if(q&&i+1<s.length()&&s.charAt(i+1)=='"'){c.append('"');i++;}else q=!q;}else if(z==','&&!q){row.add(c.toString());c.setLength(0);}else if((z=='\n'||z=='\r')&&!q){if(z=='\r'&&i+1<s.length()&&s.charAt(i+1)=='\n')i++;row.add(c.toString());c.setLength(0);if(nonempty(row))all.add(row);row=new ArrayList<>();}else c.append(z);}row.add(c.toString());if(nonempty(row))all.add(row);return all;}boolean nonempty(List<String>a){for(String s:a)if(!s.trim().isEmpty())return true;return false;}
 String pick(String[]a){return a[r.nextInt(a.length)];}String pick(List<String>a){return a.get(r.nextInt(a.size()));}
 String builtin(){switch(mode.getSelectedItemPosition()){case 1:return pick(penF)+" "+pick(penG);case 2:return pick(title);case 3:return pick(food);case 4:return pick(elements)+pick(elements)+" "+pick(elements)+pick(elements);default:return pick(family)+" "+pick(given);}}
 String imported(){if(csv==null)return"CSVを読み込んでください";String out=pick(csv.patterns);Map<Integer,StringBuilder>after=new HashMap<>();List<String>auto=new ArrayList<>();StringBuilder head=new StringBuilder(),tail=new StringBuilder();for(Row x:rows)if(x.use.isChecked()){String w=pick(x.words);int p=x.pos.getSelectedItemPosition();if(p==0)auto.add(w);else if(p==1)head.append(w).append("・");else if(p==8)tail.append("・").append(w);else{int n=p-1;if(!after.containsKey(n))after.put(n,new StringBuilder());after.get(n).append("・").append(w);}}for(Map.Entry<String,List<String>>e:csv.cols.entrySet()){String v=e.getValue().isEmpty()?"":pick(e.getValue()),add="";Matcher m=Pattern.compile("(?i)^P([1-6])$").matcher(e.getKey());if(m.matches()&&after.containsKey(Integer.parseInt(m.group(1))))add=after.get(Integer.parseInt(m.group(1))).toString();out=out.replace("["+e.getKey()+"]",v+add);}for(String w:auto)out=insert(out,w);return head+out+tail;}
 String insert(String s,String w){int p=s.indexOf(' ');return p<0?w+s:s.substring(0,p)+w+s.substring(p);}String make(){String s=mode.getSelectedItemPosition()==5?imported():builtin();if(mode.getSelectedItemPosition()!=5)for(Row x:rows)if(x.use.isChecked()){String w=pick(x.words);int p=x.pos.getSelectedItemPosition();s=p==1?w+"・"+s:p==8?s+"・"+w:insert(s,w);}return s;}
 void generate(){results.removeAllViews();for(int i=0;i<10;i++){final String value=make();TextView v=tv(String.format(Locale.JAPAN,"%02d  %s",i+1,value),19,true);v.setPadding(12,18,12,18);v.setOnLongClickListener(x->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("generated name",value));Toast.makeText(this,"コピーしました",0).show();return true;});results.addView(v);}}
}
